export const COMPANY_COUNTRIES = [
    { value: "AE", name: "United Arab Emirates" },
    { value: "AL", name: "Albania" },
    { value: "AM", name: "Armenia" },
    { value: "AR", name: "Argentina" },
    { value: "AS", name: "American Samoa" },
    { value: "AT", name: "Austria" },
    { value: "AU", name: "Australia" },
    { value: "BA", name: "Bosnia and Herzegovina" },
    { value: "BE", name: "Belgium" },
    { value: "BO", name: "Bolivia" },
    { value: "BR", name: "Brazil" },
    { value: "BS", name: "Bahamas" },
    { value: "CA", name: "Canada" },
    { value: "CF", name: "Central African Republic" },
    { value: "CH", name: "Switzerland" },
    { value: "CL", name: "Chile" },
    { value: "CN", name: "China" },
    { value: "CO", name: "Colombia" },
    { value: "CR", name: "Costa Rica" },
    { value: "CZ", name: "Czech Republic" },
    { value: "DE", name: "Germany" },
    { value: "DK", name: "Denmark" },
    { value: "DZ", name: "Algeria" },
    { value: "EE", name: "Estonia" },
    { value: "EG", name: "Egypt" },
    { value: "ES", name: "Spain" },
    { value: "FI", name: "Finland" },
    { value: "FR", name: "France" },
    { value: "GB", name: "United Kingdom" },
    { value: "GH", name: "Ghana" },
    { value: "GR", name: "Greece" },
    { value: "HK", name: "Hong Kong" },
    { value: "HN", name: "Honduras" },
    { value: "HR", name: "Croatia" },
    { value: "HU", name: "Hungary" },
    { value: "ID", name: "Indonesia" },
    { value: "IE", name: "Ireland" },
    { value: "IL", name: "Israel" },
    { value: "IN", name: "India" },
    { value: "IQ", name: "Iraq" },
    { value: "IR", name: "Iran" },
    { value: "IT", name: "Italy" },
    { value: "JP", name: "Japan" },
    { value: "KE", name: "Kenya" },
    { value: "LT", name: "Lithuania" },
    { value: "LU", name: "Luxembourg" },
    { value: "LV", name: "Latvia" },
    { value: "MA", name: "Morocco" },
    { value: "MD", name: "Moldova" },
    { value: "MK", name: "North Macedonia" },
    { value: "MT", name: "Malta" },
    { value: "MX", name: "Mexico" },
    { value: "MY", name: "Malaysia" },
    { value: "NG", name: "Nigeria" },
    { value: "NL", name: "Netherlands" },
    { value: "NZ", name: "New Zealand" },
    { value: "PH", name: "Philippines" },
    { value: "PK", name: "Pakistan" },
    { value: "PL", name: "Poland" },
    { value: "PR", name: "Puerto Rico" },
    { value: "PT", name: "Portugal" },
    { value: "RO", name: "Romania" },
    { value: "RU", name: "Russia" },
    { value: "SE", name: "Sweden" },
    { value: "SG", name: "Singapore" },
    { value: "SI", name: "Slovenia" },
    { value: "SK", name: "Slovakia" },
    { value: "TH", name: "Thailand" },
    { value: "TR", name: "Turkey" },
    { value: "UA", name: "Ukraine" },
    { value: "US", name: "United States" },
    { value: "VN", name: "Vietnam" },
];

export const EMPLOYEE_RESIDENCES = [
    { value: "AE", name: "United Arab Emirates", count: 3 },
    { value: "AM", name: "Armenia", count: 1 },
    { value: "AR", name: "Argentina", count: 6 },
    { value: "AS", name: "American Samoa", count: 2 },
    { value: "AT", name: "Austria", count: 6 },
    { value: "AU", name: "Australia", count: 11 },
    { value: "BA", name: "Bosnia and Herzegovina", count: 1 },
    { value: "BE", name: "Belgium", count: 5 },
    { value: "BG", name: "Bulgaria", count: 1 },
    { value: "BO", name: "Bolivia", count: 3 },
    { value: "BR", name: "Brazil", count: 18 },
    { value: "CA", name: "Canada", count: 85 },
    { value: "CF", name: "Central African Republic", count: 2 },
    { value: "CH", name: "Switzerland", count: 4 },
    { value: "CL", name: "Chile", count: 2 },
    { value: "CN", name: "China", count: 1 },
    { value: "CO", name: "Colombia", count: 4 },
    { value: "CR", name: "Costa Rica", count: 1 },
    { value: "CY", name: "Cyprus", count: 1 },
    { value: "CZ", name: "Czech Republic", count: 2 },
    { value: "DE", name: "Germany", count: 48 },
    { value: "DK", name: "Denmark", count: 3 },
    { value: "DO", name: "Dominican Republic", count: 1 },
    { value: "DZ", name: "Algeria", count: 1 },
    { value: "EE", name: "Estonia", count: 1 },
    { value: "EG", name: "Egypt", count: 1 },
    { value: "ES", name: "Spain", count: 80 },
    { value: "FI", name: "Finland", count: 2 },
    { value: "FR", name: "France", count: 38 },
    { value: "GB", name: "United Kingdom", count: 167 },
    { value: "GH", name: "Ghana", count: 2 },
    { value: "GR", name: "Greece", count: 16 },
    { value: "HK", name: "Hong Kong", count: 2 },
    { value: "HN", name: "Honduras", count: 1 },
    { value: "HR", name: "Croatia", count: 3 },
    { value: "HU", name: "Hungary", count: 3 },
    { value: "ID", name: "Indonesia", count: 1 },
    { value: "IE", name: "Ireland", count: 7 },
    { value: "IL", name: "Israel", count: 1 },
    { value: "IN", name: "India", count: 71 },
    { value: "IQ", name: "Iraq", count: 1 },
    { value: "IR", name: "Iran", count: 1 },
    { value: "IT", name: "Italy", count: 8 },
    { value: "JE", name: "Jersey", count: 1 },
    { value: "JP", name: "Japan", count: 7 },
    { value: "KE", name: "Kenya", count: 2 },
    { value: "KW", name: "Kuwait", count: 1 },
    { value: "LT", name: "Lithuania", count: 2 },
    { value: "LU", name: "Luxembourg", count: 1 },
    { value: "LV", name: "Latvia", count: 4 },
    { value: "MA", name: "Morocco", count: 1 },
    { value: "MD", name: "Moldova", count: 1 },
    { value: "MK", name: "North Macedonia", count: 1 },
    { value: "MT", name: "Malta", count: 1 },
    { value: "MX", name: "Mexico", count: 10 },
    { value: "MY", name: "Malaysia", count: 1 },
    { value: "NG", name: "Nigeria", count: 7 },
    { value: "NL", name: "Netherlands", count: 15 },
    { value: "NZ", name: "New Zealand", count: 1 },
    { value: "PH", name: "Philippines", count: 2 },
    { value: "PK", name: "Pakistan", count: 8 },
    { value: "PL", name: "Poland", count: 6 },
    { value: "PR", name: "Puerto Rico", count: 5 },
    { value: "PT", name: "Portugal", count: 18 },
    { value: "RO", name: "Romania", count: 3 },
    { value: "RS", name: "Serbia", count: 1 },
    { value: "RU", name: "Russia", count: 4 },
    { value: "SE", name: "Sweden", count: 2 },
    { value: "SG", name: "Singapore", count: 5 },
    { value: "SI", name: "Slovenia", count: 4 },
    { value: "SK", name: "Slovakia", count: 1 },
    { value: "TH", name: "Thailand", count: 3 },
    { value: "TN", name: "Tunisia", count: 1 },
    { value: "TR", name: "Turkey", count: 5 },
    { value: "UA", name: "Ukraine", count: 4 },
    { value: "US", name: "United States", count: 3004 },
    { value: "UZ", name: "Uzbekistan", count: 2 },
    { value: "VN", name: "Vietnam", count: 3 },
];

export const LEVELS = [
    { value: "EN", name: "Junior" },
    { value: "MI", name: "Semi Senior" },
    { value: "SE", name: "Senior" },
    { value: "EX", name: "Ejecutivo" },
];

export const JOB_POSITIONS = [
    { value: "Data Analyst", name: "Data Analyst" },
    { value: "Data Scientist", name: "Data Scientist" },
    { value: "Data Engineer", name: "Data Engineer" },
    { value: "Machine Learning Engineer", name: "Machine Learning Engineer" },
    {
        value: "Computer Vision / Deep Learning",
        name: "Computer Vision / Deep Learning",
    },
    {
        value: "Data Leadership / Management",
        name: "Data Leadership / Management",
    },
    {
        value: "Data Architect / Infrastructure",
        name: "Data Architect / Infrastructure",
    },
    { value: "Data Analytics", name: "Data Analytics" },
    { value: "Data Operations / Quality", name: "Data Operations / Quality" },
    { value: "Data Governance / Strategy", name: "Data Governance / Strategy" },
    { value: "Research Engineer", name: "Research Engineer" },
];

export const COMPANY_SIZES = [
    {
        value: "S",
        name: "Start-up",
    },
    {
        value: "M",
        name: "Mediana empresa",
    },
    {
        value: "L",
        name: "Gran empresa",
    },
];

export const MODALITIES = [
    {
        value: 0,
        name: "Presencial",
    },
    {
        value: 50,
        name: "Híbrido",
    },
    {
        value: 100,
        name: "Remoto",
    },
];

export const CONTRACT_TYPES = [
    {
        value: "FT",
        name: "Tiempo completo",
    },
    {
        value: "PT",
        name: "Medio tiempo",
    },
    {
        value: "CT",
        name: "Contrato",
    },
    {
        value: "FL",
        name: "Freelance",
    },
];
