export const COUNTRIES = [
    { value: "US", name: "United States" },
    { value: "GB", name: "Great Britain" },
    { value: "CA", name: "Canada" },
    { value: "ES", name: "Spain" },
    { value: "IN", name: "India" },
    { value: "DE", name: "Germany" },
    { value: "FR", name: "France" },
    { value: "PT", name: "Portugal" },
    { value: "BR", name: "Brazil" },
    { value: "GR", name: "Greece" },
    { value: "NL", name: "Netherlands" },
    { value: "AU", name: "Australia" },
    { value: "MX", name: "Mexico" },
    { value: "IT", name: "Italy" },
    { value: "PK", name: "Pakistan" },
    { value: "JP", name: "Japan" },
    { value: "IE", name: "Ireland" },
    { value: "NG", name: "Nigeria" },
    { value: "AT", name: "Austria" },
    { value: "AR", name: "Argentina" },
    { value: "PL", name: "Poland" },
    { value: "PR", name: "Puerto Rico" },
    { value: "TR", name: "Turkey" },
    { value: "BE", name: "Belgium" },
    { value: "SG", name: "Singapore" },
    { value: "RU", name: "Russia" },
    { value: "LV", name: "Latvia" },
    { value: "UA", name: "Ukraine" },
    { value: "CO", name: "Colombia" },
    { value: "CH", name: "Switzerland" },
    { value: "SI", name: "Slovenia" },
    { value: "BO", name: "Bolivia" },
    { value: "DK", name: "Denmark" },
    { value: "HR", name: "Croatia" },
    { value: "HU", name: "Hungary" },
    { value: "RO", name: "Romania" },
    { value: "TH", name: "Thailand" },
    { value: "AE", name: "United Arab Emirates" },
    { value: "VN", name: "Vietnam" },
    { value: "HK", name: "Hong Kong" },
    { value: "UZ", name: "Uzbekistan" },
    { value: "PH", name: "Philippines" },
    { value: "CF", name: "Central African Republic" },
    { value: "CL", name: "Chile" },
    { value: "FI", name: "Finland" },
    { value: "CZ", name: "Czech Republic" },
    { value: "SE", name: "Sweden" },
    { value: "AS", name: "American Samoa" },
    { value: "LT", name: "Lithuania" },
    { value: "GH", name: "Ghana" },
    { value: "KE", name: "Kenya" },
    { value: "DZ", name: "Algeria" },
    { value: "NZ", name: "New Zealand" },
    { value: "JE", name: "Jersey" },
    { value: "MY", name: "Malaysia" },
    { value: "MD", name: "Moldova" },
    { value: "IQ", name: "Iraq" },
    { value: "BG", name: "Bulgaria" },
    { value: "LU", name: "Luxembourg" },
    { value: "RS", name: "Serbia" },
    { value: "HN", name: "Honduras" },
    { value: "EE", name: "Estonia" },
    { value: "TN", name: "Tunisia" },
    { value: "CR", name: "Costa Rica" },
    { value: "ID", name: "Indonesia" },
    { value: "EG", name: "Egypt" },
    { value: "DO", name: "Dominican Republic" },
    { value: "CN", name: "China" },
    { value: "SK", name: "South Korea" },
    { value: "IR", name: "Iran" },
    { value: "MA", name: "Morocco" },
    { value: "IL", name: "Israel" },
    { value: "MK", name: "North Macedonia" },
    { value: "BA", name: "Bosnia" },
    { value: "AM", name: "Armenia" },
    { value: "CY", name: "Cyprus" },
    { value: "KW", name: "Kuwait" },
    { value: "MT", name: "Malta" },
    { value: "BS", name: "The Bahamas" },
    { value: "AL", name: "Albania" },
];

export const LEVELS = [
    { value: "junior", name: "Junior" },
    { value: "semi-senior", name: "Semi Senior" },
    { value: "senior", name: "Senior" },
];

export const JOB_POSITIONS = [
    { value: "frontend", name: "Frontend Developer" },
    { value: "backend", name: "Backend Developer" },
    { value: "fullstack", name: "Fullstack Developer" },
    { value: "qa", name: "Quality Assurance" },
    { value: "ux-ui", name: "UX/UI Designer" },
    { value: "devops", name: "DevOps Engineer" },
    { value: "project-manager", name: "Project Manager" },
];
